### ISSUE TITLE
Filename not supported in Windows

### ISSUE THREAD

**Issue by iCrashed** [BatuhanUsluel/Algorithmic-Support-and-Resistance#1]
When I cloned the project and tried to run it I got the error

`'Resistance.py' is not recognized as an internal or external command,`

Maybe filename with & is not supported in windows.  When I changed the file name to ps.py it worked.

**Comment by BatuhanUsluel** [comment]
I run it on windows without problems, but I changed the filename in case anyone else has the same problem. Thanks for bringing it up.
