### ISSUE TITLE
'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by iCrashed** [BatuhanUsluel/Algorithmic-Support-and-Resistance#2]
When I run the program,  in the console under most of the company symbol's name I get the following error

`'DataFrame' object has no attribute 'ix'`

some companies (like ATVI, ADBE, AMD) don't have this under their names. 

and no chart is generated.

**Comment by BatuhanUsluel** [comment]
Fixed. The issue was that pandas deprecated the ix indexer, but I was using an old version which still supported it. Should be working now with new versions.

**Comment by iCrashed** [comment]
working 👍  :)
